### ISSUE TITLE
Seal Images

### ISSUE THREAD

**Issue by xvrabcov** [xvrabcov/fithesis#20]
Currently we are using logo images in the macro seal but seeing as the Pharm Faculty does not have one, in the interest of unity, it might be prudent to replace the logos with seals of the same style as the Pharm Faculty.

![image](https://user-images.githubusercontent.com/77483907/112603729-ae9e4f00-8e15-11eb-91f4-c2045f34db22.png)

**Comment by Witiko** [comment]
I would suggest keeping both old-style and new-style seals, perhaps enabled/disabled by a conditional (`\ifthesis@oldseals@`) defined in `base.dtx` and set in the faculty style files. We can patch `\includegraphics`, so that when it tries to include an old-style seal and can't find the file, it will fall back to the new-style seal, similar to how mubeamer does it: https://gitlab.ics.muni.cz/409729/mubeamer/-/blob/master/mubeamer.dtx#L507

**Comment by xvrabcov** [comment]
I have added a dir new_seals with pdf files of the new faculty logos into the feature/university-logo branch.
