### ISSUE TITLE
Adding Summary

### ISSUE THREAD

**Issue by xvrabcov** [xvrabcov/fithesis#6]
Arts (FF) and Econ (ESF) Faculties have summary (resumé) as one of the mandatory parts of the doctoral thesis. [Here is an example](https://www.overleaf.com/read/vcsvqjwqbcgj) of how it can be added.

Furthermore, Econ Faculty wants its summary to be in English even when the language of the thesis is Czech/Slovak. Arts Faculty does not state any further restrictions.

**Comment by Witiko** [comment]
The failure of 684b6e623548e2c8f17b82dc092d5ed9d6b7948d is likely due to the `extra = { summary = {...} }` code in `example.dtx`:

https://github.com/xvrabcov/fithesis/blob/684b6e623548e2c8f17b82dc092d5ed9d6b7948d/example/mu/example.dtx#L160

Since `summary` is defined in the base namespace, the correct form would be `summary = {...}`:

https://github.com/xvrabcov/fithesis/blob/684b6e623548e2c8f17b82dc092d5ed9d6b7948d/fithesis.dtx#L1230

However, perhaps it would be best to define summary and summaryEn as extra key for FF and ESF using the `\thesis@def@extra` command, so that we don't bloat the base namespace with keys that are seldom used:

https://github.com/xvrabcov/fithesis/blob/684b6e623548e2c8f17b82dc092d5ed9d6b7948d/fithesis.dtx#L1483

See for example how PřF uses `\thesis@def@extra`:

https://github.com/xvrabcov/fithesis/blob/684b6e623548e2c8f17b82dc092d5ed9d6b7948d/style/mu/sci.dtx#L292

https://github.com/xvrabcov/fithesis/blob/684b6e623548e2c8f17b82dc092d5ed9d6b7948d/example/mu/example.dtx#L518
